name: CI

on:
  push:
    branches:
      - develop
      - feature/*
  pull_request:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_USER: shopEaseUser
          POSTGRES_PASSWORD: shopEasePass
          POSTGRES_DB: shopEaseUserDB
        ports:
          - 5432:5432
        options: >-
          --health-cmd "pg_isready -U shopEaseUser"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          cd services/user_service
          pip install -r requirements.txt

      - name: Run tests
        run: |
          cd services/user_service
          pytest
